package com.a5.ngenemichael.quotes;

public class AllQuotes {

    public String [] greatness = {"\" Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.\"",
            "”Great spirits have always encountered violent opposition from mediocre minds.-”",
            "“Simplicity is the keynote of all true elegance.”-",
            "“Don't blow off another's candle for it won't make yours shine brighter.”",
            "“I was never afraid of failure; for I would sooner fail than not be among the greatest.”",
            "“Nothing is more simple than greatness; indeed, to be simple is to be great.”",
            "“Don't set your goals by what other people deem important.”",
            "“The greatness of humanity is not in being human, but in being humane.”",
            "“The final proof of greatness lies in being able to endure criticism without resentment.”",
            "“Your greatness is revealed not by the lights that shine upon you, but by the light that shines within you.”",
            "“When you're good at something, you'll tell everyone. When you're great at something, they'll tell you.”",
            "“The past is to be respected and acknowledged, but not worshipped; it is our future in which we will find our greatness.”",
            "“Maybe if we stopped trying to achieve movie standards of greatness, we'd be happy”",
           "“The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward”",
            "“Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself. ”",
            "“ Learning never exhausts the mind.”",
            "“Live as if you were to die tomorrow. Learn as if you were to live forever.”",
            "“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment”",
            "“To live is the rarest thing in the world. Most people exist, that is all”",
            "“Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. ”",
            "“That which does not kill us makes us stronger ”",
            "“God does not create a lock without its key & God does not give you problems without its solutions! TRUST HIM ”",
            "“Life is too short to start your day with broken pieces of yesterday, it will definitely destroy your wonderful today and ruin your great tomorrow.”",
            "“Respect yourself enough to walk away from anything that no longer serves you, grows you, or makes you happy.”",

            /////////////////////////////////////////////////////////////////////////////////////////////////////
            "“A man once told The Buddha, “I want happiness.”\n" +
                    "\n" +
                    "The Buddha replied, “First remove “I”, that’s ego. Then remove “want”, that’s desire. And now all you’re left with is Happiness.” ”",
            ///////////////////////////////////////////////////////////////////////////////////////////
            "“When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down “happy”. They told me I didn’t understand the assignment, I told them they didn’t understand life.”",
            "“Expect the best, be prepared for the worst, fuck what others think & do your own thing”",
            "“Never tell your problems to anyone. 20% don’t care and the other 80% are glad you have them.”",
            "“If you repeat a lie often enough, it becomes politics.”",
            "“Stop waiting for things to happen. Go out and make them happen.”",
            "“If you’re not failing every now and again, it’s a sign you’re not doing anything very innovative. ”",
            "“The greatest pleasure in life is doing what people say you cannot do”",
            "“If ever there is a tomorrow when we’re not together… there is something you must always remember, you are braver than you believe, stronger than you seem & smarter than you think even if we’re apart … I’ll always be with you.”",
            "“Success is the sum of small efforts, repeated day in and day out”",
            "“It’s hard to wait around for something you know might never happen; but it’s even harder to give up when you know it’s everything you want”",
            "“Keep on criticizing, insulting and judging other people. Someday, someone will do the same to you. Karma do exist dear.”",
            "“Just because someone doesn’t love you the way you want them to, doesn’t mean they don’t love you with everything they have.”",
            "“Waiting hurts. Forgetting gurts. But not knowing which decision to take is the worst of suffering.”",
            "“I think we’re just gonna have to be secretly in love with each other and leave it at that”",
            "“Be confident. Too many days are wasted comparing ourselves to others and wishing to be something we aren’t. Everybody has their own strengths and weaknesses, and it is only when you accept everything you are – and aren’t – that you will truly succeed.”",
            "“Never play with feelings of others because you may win the game but the risk is that you will surely lose the person for a life time”",
            "“The world suffers a lot. Not because of the violence of bad people. But because of the silence of good people.”",
            "“I am thankful to those who said NO to me it’s because of them I did it myself.”",
            "“If friendship is your weakest point then you are the strongest person in the world.”",
            "“We must learn to live together as brothers or we will perish together as fools.”",
            "“The weak can never forgive. Forgiveness is the attribute of the strong.”",
            "“It is very easy to defeat someone, but it is very hard to win someone.”",
            "“Don’t ever let someone tell you that you can’t do something. not even me. You got a dream, you gotta protect it. When people can’t do something themselves, they’re gonna tell you that you can’t do it. You want something, go get it. Period”",
            "“Logic will get you from A-Z. Imagination will get you everywhere”",
            "“Life is too short to wake up in the morning with regrets. So love the people who treat you right and forget the ones that don’t and believe that everything happens for a reason. If you get a chance, take it. If it changes your life, let it. Nobody said it’d be easy, they just promised it would be worth it.”",
            "“The naked truth is always better than the best-dressed lie.”",
            "“If you don’t go after what you want, you’ll neve have it. If you don’t ask, the answer is always no. If you don’t step forward, you’re always in the same place”",
            "“Give, But Don't Allow Yourself To Be Used\n" +
                    "Love, But Don't Allow Your Heart To Be Abused\n" +
                    "Trust, But Don't Be Naive\n" +
                    "Listen To Others, But Don't Lose Your Own Voice”",
            "“Complaining About A Problem Without Posing A Solution Is Called Whining”",
            "“Fake People Have An Image To Maintain. Real People Just Don't Care”",
            "“Worrying Is Like Walking Around With An Umbrella Waiting For It To Rain”",
            "“Don't Feel Guilty For Doing What's Best For You”",
            "“Years Of Love Have Been Forgotten In The Hatred Of A Minute”",
            "“Everyday Is A Second Chance”",
            "“Will It Be Easy?, No. Will It Be Worth It?, Absolutely!”",
            "“A Mistake Repeated More Than Once Is A Decision”",
            "“A Secret To Happiness Is Letting Every Situation Be What It Is, Instead Of What You Think It Should Be”",
            "“I Am Imperfect And Yet My Imperfections, Like Any Great Work Of Art, Are What Make Me A Masterpiece”",
            "“Never Quit. If You Stumble Get Back Up. What Happened Yesterday No Longer Matters. Today Is Another Day So Get On Track And Move Closer To Your Dreams And Goals. You Can Do It.”",
            "“Always Remember You Are Braver Than You Believe. Stronger Than You Seem. Smarter Than You Think, And Twice As Beautiful As You've Ever Imagined.”",
            "“We Either Make Ourselves Miserable Or We Make Ourselves Strong. The Amount Of Work Is The Same”",
            "“You Don't Have To Be Great To Start, But You Have To Start To Be Great”",
            "“Life is choice. All Day, everyday. Who we talk to, where we sit, what we say, how we say it. And our lives become defined by our choices. It's as simple and as complex as that, and as powerful”",
            "“You Are Unstoppable Not Because You Do Not Have Failures Or Doubts. You Are Unstoppable Because You Carried On Despite Them”",
            "“You Will Never Have This Day Again So Make It Count”",
            "“Someone Fell In Love Today. Someone Was Born Today. Someone Lived Through Something That Could Have Killed Them. Someone Won Back The Love Of Their Life. Someone Made Their Parents Proud. Someone Survived. Someone Healed. Someone Let Go. Seven Billion People, And Some Of Us Have Just Had The Best Day Of Our Lives. Today May Have Been The Very Worst Day Of Yours. But Take Solace And Celebrate This Simple Fact. It Wasn't Your Best Day Today, But It Is On It's Way, Because We All Get Lucky In Turn”",
            "“Characterize People By Their Actions And You Will Never Be Fooled By Their Words”",
            "“Your Work Is Going To Fill A Large Part Of Your Life, And The Only Way To Be Truly Satisfied Is Great Work. The Only Way To Do Great Work Is To Love What You Do”",
            "“I will forever remain humble because I know I could have less. I will always be grateful because I know I've had less”",
            "“You Can Never Cross The Ocean Until You Have The Courage To Lose Sight Of The Shore”",
            "“Never Accept Anything Less Than You Deserve. Remember, You Teach People How To Treat You”",
            "“Many Great Things Can Be Done In A Day. If You Don't Always Make That Day Tomorrow”",
            "“Surround Yourself With The Dreamers And The Doers, The Believers And The Thinkers, But Most Of All, Surround Yourself With Those Who See Greatness Within You, Even When You Don't See It Yourself”",
            "“Be Stubborn About Your Goals, And Flexible About Your Methods”",
            "“Never Apologize For Having High Standards. People Who Really Want To Be In Your Life Will Rise Up To Meet Them”",
            "“Bad News: You're Not Going To Fit In With Everyone.\n" +
                             "Good News: The Great Ones Never Do”",
            "“It's Not About Being The Best, It's About Being Better Than You Were Yesterday”",
            "“Learning To Ignore Things Is One Of the Great Paths To Inner Peace”",
            "“You Either Get Bitter Or You Get Better. It's That Simple. You Either Take What Has Been Dealt To You And Allow It To Make You A Better Person, Or You Allow It To Tear You Down. The Choice Does Not Belong To Fate, It Belongs To You”",
            "“Most Of The Problems In Life Come Because Of Two Reasons: We Act Without Thinking, And We Keep Thinking Without Acting”",
            "“The Greatest Prison People Live In, Is the Fear Of What People Think”",
            "“Your Smile Is Your* _*Logo*_, *Your Personality Is Your* _*Business Card*_, *How You Leave Others Feeling After An Experience With You Becomes Your* _*Trademark”",
            "“Your Relationship With Yourself Sets The Tone For Every Other Relationship You Have”",
            "“You Can't Make Everybody Happy”",
            "“Every Positive Change In Your Life Begins With A Clear Decision That You Are Either Going To Do Something Or Stop Doing Something”",
            "“Don't Raise Your Voice, Improve Your Argument!”",
            "“Do All The Good You Can, By All The Means You Can, In All The Ways You Can, In All The Places You Can, At All The Times You Can, To All The People You Can, As Long As Ever You Can”",
            "“Remember How Far You've Come, Not Just How Far You Have To Go. You Are Not Where You Want To Be, But Neither Are You Where You Used To Be”",
            "“If You Want To Be Happy, You Have To Be Happy On Purpose. When You Wake Up You Can't Just Wait To See What Kind Of Day You'll Have. You Have To Decide What Kind Of Day You'll Have”",
           /* "“”",
            "“”",
            "“”",
            "“”",*/
    };

    public String [] names = {"William Shakespeare",
            "Albert Einstein",
            "Coco Chanel",
            "Jaachynma N.E. Agu",
            "John Keats",
            "Ralph Waldo Emerson",
            "Jaachynma N.E. Agu",
            "Mahatma Gandhi",
            "Elbert Hubbard",
            "Ray A. Davis",
            "Walter Payton",
            "Pierre Trudeau",
            "Amber L. Johnson",
            "Amelia Earhart",
            "Henry James ",
            "Leonardo da Vinci",
            "Mahatma Gandhi ",
            "Ralph Waldo Emerson",
            "Oscar Wilde",
            "Bil Keane",
            "Friedrich Nietzsche",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "John Lennon",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Woody Allen",
            "Walter Bagehot",
            "A. A. Milne",
            "R. Collier",
            "Unknown",
            "Unknown",
            "Unknown",
            "Paolo Coelho",
            "Margot Tenenbaum",
            "Unknown",
            "Shakespeare",
            "Napoleon",
            "Einstein",
            "Abraham Lincoln",
            "Martin Luther King",
            "Mahatma Gandhi:",
            "Dr. Abdul Kalaam",
            "Will Smith",
            "Albert Einstein",
            "Anonymous",
            "Unknown",
            "Unknown",
            "Unknown",
            "Teddy Roosevelt",
            "Unknown",
            "Unknown",
            "Unknown",
            "Edgar Ullan Poe",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Kelsey Silver",
            "Unknown",
            "Dr. Seuss.",
            "Carlos Castenada",
            "Unknown",
            "Louise Penny",
            "Unknown",
            "Unknown",
            "Nikita Gill",
            "Unknown",
            "Unknown",
            "Unknown",
            "Christopher Columbus",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Robert J. Sawyer",
            "Josh Ship",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "Unknown",
            "John Wesley",
            "Rick Warren",
            "Joel Osteen",
          /*  "",
            "",
            "",
            "",
            */
    };

    public AllQuotes(){}

    public String[] getGreatness() {
        return greatness;
    }

    public String[] getNames() {
        return names;
    }
}
